Run Information
========================
cognizant.intelligent.test.scripter.engine : 1.4
java.runtime.name    : Java(TM) SE Runtime Environment
java.version         : 11.0.8
java.home            : C:\Program Files\Java\jdk-11.0.8
os.name              : Windows 10
os.arch              : amd64
os.version           : 10.0
file.encoding        : UTF-8
========================
Run Started on Thu Oct 08 14:26:26 BST 2020
Loading Browser Profile
Loading RunManager
[Scenario:Home EAgro] [TestCase: Search Cotton] [Description: Test Run] [Browser: Chrome] [BrowserVersion: default] [Platform: ANY][ExistingBrowser: false]
Initializing Report
ApiLink not available!!
Run Manager true
Continue Execution true
Shutting Down Thread as there is no need for SelectiveThreading
Inside Task Run
Running Iteration 1
Launching Chrome
Launching Local Driver
Starting ChromeDriver 85.0.4183.87 (cd6713ebf92fa1cacc0f1a598df280093af0c5d7-refs/branch-heads/4183@{#1689}) on port 27880
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
2020-10-08 14:26:30:10S +0100 [INFO] org.openqa.selenium.remote.ProtocolHandshake createSession:Detected dialect: W3C
Chrome Launched
Step:1   | Object: Browser | Action: Open | Input: TestData0:URL | Conditon:  | @08-Oct-2020 14:26:30.030
[DEBUG]   | Test Data Not Found, Iteration - 1 is missing. 
[Env : Default | Sheet : TestData0 | Field : URL | TestCase : Home EAgro/Search Cotton | Reusabe : Home EAgro/EAgro_Login ]

===================================================================================================

2020-10-08 14:26:30:10S +0100 [SEVERE] com.cognizant.cognizantits.engine.core.Task onError:Error in testcase [//Home EAgro/EAgro_Login]
com.cognizant.cognizantits.engine.execution.exception.TestFailedException: Error in testcase [//Home EAgro/EAgro_Login]
	at com.cognizant.cognizantits.engine.execution.run.TestCaseRunner.onDataNotFoundException(TestCaseRunner.java:306)
	at com.cognizant.cognizantits.engine.execution.run.TestCaseRunner.run(TestCaseRunner.java:350)
	at com.cognizant.cognizantits.engine.execution.run.TestCaseRunner.run(TestCaseRunner.java:387)
	at com.cognizant.cognizantits.engine.execution.run.TestStepRunner.executeTestCase(TestStepRunner.java:137)
	at com.cognizant.cognizantits.engine.execution.run.TestStepRunner.execute(TestStepRunner.java:118)
	at com.cognizant.cognizantits.engine.execution.run.TestStepRunner.run(TestStepRunner.java:63)
	at com.cognizant.cognizantits.engine.execution.run.TestCaseRunner.runStep(TestCaseRunner.java:395)
	at com.cognizant.cognizantits.engine.execution.run.TestCaseRunner.run(TestCaseRunner.java:346)
	at com.cognizant.cognizantits.engine.core.Task.runIteration(Task.java:130)
	at com.cognizant.cognizantits.engine.core.Task.run(Task.java:85)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: Test Data Not Found, Iteration - 1 is missing. 
[Env : Default | Sheet : TestData0 | Field : URL | TestCase : Home EAgro/Search Cotton | Reusabe : Home EAgro/EAgro_Login ]
	at com.cognizant.cognizantits.engine.execution.data.DataAccessInternal.throwErrorWithCause(DataAccessInternal.java:287)
	at com.cognizant.cognizantits.engine.execution.data.DataAccess.getData(DataAccess.java:71)
	at com.cognizant.cognizantits.engine.execution.data.DataProcessor.resolve(DataProcessor.java:64)
	at com.cognizant.cognizantits.engine.core.CommandControl.sync(CommandControl.java:168)
	at com.cognizant.cognizantits.engine.execution.run.TestStepRunner.executeStep(TestStepRunner.java:160)
	at com.cognizant.cognizantits.engine.execution.run.TestStepRunner.executeStep(TestStepRunner.java:147)
	at com.cognizant.cognizantits.engine.execution.run.TestStepRunner.run(TestStepRunner.java:66)
	at com.cognizant.cognizantits.engine.execution.run.TestCaseRunner.runStep(TestCaseRunner.java:395)
	at com.cognizant.cognizantits.engine.execution.run.TestCaseRunner.run(TestCaseRunner.java:346)
	... 11 more

[DEBUG]   | Error in testcase [//Home EAgro/EAgro_Login]

===================================================================================================


---------------------------------------------------
Testcase Name        : Home EAgro:Search Cotton
Executed Steps       : 2
Passed Steps         : 0
Failed Steps         : 2
Time Taken           : 00:00:04
-----------------------------------------------------

Run Finished on Thu Oct 08 14:26:31 BST 2020
-----------------------------------------------------
ExecutionDate        : 08-Oct-2020 14-26-26
Executed TestCases   : 1
Passed TestCases     : 0
Failed TestCases     : 1
Time Taken           : 00:00:04
ReportPath           : file:///C:\Working\Automation\cognizant-intelligent-test-scripter-1.4-setup\cognizant-intelligent-test-scripter-1.4\Projects\Appian Europe Conference\Results\TestDesign\Home EAgro\Search Cotton\08-Oct-2020 14-26-26\summary.html
-----------------------------------------------------
